# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Hi.Larry.Us a blog about family and amusement
url:   http://hilarry.us
author:
  name:    Larry Cummings   # For copyright notice and ATOM feeds
  email:   larry@Larry.org  # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://lars30.myopenid.com
      - http://plus.google.com/103346936939198267791

# Delete the following section if your site will not be acting as an OpenID delegate (http://wiki.openid.net/Delegation)
# If you're deploying with mongrel, make sure you read http://rhnh.net/2008/04/13/nginx-openid-delegation-and-yadis
# open_id_delegation:
#   server:   http://www.myopenid.com/server
#   delegate: http://username.myopenid.com
